
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Stats
{ 
    public enum StatType
    {
        Strength = 0,
        Intelligence = 1,
        Willpower = 2,
        Dexterity = 3,
        WeaponDamage = 4,
        AttackSpeed = 5,
        CriticalChance = 6,
        CriticalDamage = 7,
        FireDamage = 8,
        ColdDamage = 9,
        LightningDamage = 10,
        PoisonDamage = 11,
        PhysicalDamage = 12,
        OverPowerDamage = 13,
        VulnerableDamage = 14,
        Armor = 15,
        MaxHealth = 16,
        MaxMana = 17,
        DamageReduction = 18,
        FireResistance = 19,
        ColdResistance = 20,
        LightningResistance = 21,
        PoisonResistance = 22,
        PhysicalResistance = 23,
        AllResistance = 24,
        DodgeChance = 25,
        HealingReceived = 26,
        LuckyHitChance = 27,
        CooldownReduction = 28,
        ResourceCostReduction = 29,
        SkillRanks = 30,
        MovementSpeed = 31,
        Thorns = 32,
    }

} 

