
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Stats
{ 
    public enum StatType
    {
        Strength = 0,
        Intelligence = 1,
        Willpower = 2,
        Dexterity = 3,
        WeaponDamage = 4,
        AttackSpeed = 5,
        CriticalChance = 6,
        CriticalDamage = 7,
        FireDamage = 8,
        ColdDamage = 9,
        LightningDamage = 10,
        PhysicalDamage = 11,
        OverPowerDamage = 12,
        VulnerableDamage = 13,
        Armor = 14,
        MaxHealth = 15,
        MaxMana = 16,
        DamageReduction = 17,
        FireResistance = 18,
        ColdResistance = 19,
        LightningResistance = 20,
        PhysicalResistance = 21,
        DodgeChance = 22,
        HealingReceived = 23,
        LuckyHitChance = 24,
        CooldownReduction = 25,
        ResourceCostReduction = 26,
        SkillRanks = 27,
        MovementSpeed = 28,
        Thorns = 29,
    }

} 

