
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.Maps
{
public sealed partial class MapInfo : Luban.BeanBase
{
    public MapInfo(JsonElement _buf) 
    {
        Id = _buf.GetProperty("id").GetString();
        Name = _buf.GetProperty("name").GetString();
        SceneName = _buf.GetProperty("scene_name").GetString();
    }

    public static MapInfo DeserializeMapInfo(JsonElement _buf)
    {
        return new Maps.MapInfo(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// name
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// scene_name
    /// </summary>
    public readonly string SceneName;
   
    public const int __ID__ = 1971252179;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "sceneName:" + SceneName + ","
        + "}";
    }
}

}

