
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.Mobs
{
public partial class TbMobs
{
    private readonly System.Collections.Generic.Dictionary<string, CharacterInfo> _dataMap;
    private readonly System.Collections.Generic.List<CharacterInfo> _dataList;
    
    public TbMobs(JsonElement _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, CharacterInfo>();
        _dataList = new System.Collections.Generic.List<CharacterInfo>();
        
        foreach(JsonElement _ele in _buf.EnumerateArray())
        {
            CharacterInfo _v;
            _v = CharacterInfo.DeserializeCharacterInfo(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, CharacterInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<CharacterInfo> DataList => _dataList;

    public CharacterInfo GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public CharacterInfo Get(string key) => _dataMap[key];
    public CharacterInfo this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

