
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
public sealed partial class StatsInfo : Luban.BeanBase
{
    public StatsInfo(JsonElement _buf) 
    {
        MaxHealth = _buf.GetProperty("max_health").GetSingle();
        Speed = _buf.GetProperty("speed").GetSingle();
    }

    public static StatsInfo DeserializeStatsInfo(JsonElement _buf)
    {
        return new StatsInfo(_buf);
    }

    public readonly float MaxHealth;
    public readonly float Speed;
   
    public const int __ID__ = -69315123;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "maxHealth:" + MaxHealth + ","
        + "speed:" + Speed + ","
        + "}";
    }
}

}

