
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;

namespace cfg
{
public partial class Tables
{
    public TbConstants TbConstants {get; }
    public Characters.TbCharacters TbCharacters {get; }
    public Maps.TbMaps TbMaps {get; }
    public Items.TbItems TbItems {get; }
    public Mobs.TbMobs TbMobs {get; }
    public Items.TbAffixes TbAffixes {get; }
    public Items.TbEquipment TbEquipment {get; }

    public Tables(System.Func<string, JsonElement> loader)
    {
        TbConstants = new TbConstants(loader("tbconstants"));
        TbCharacters = new Characters.TbCharacters(loader("characters_tbcharacters"));
        TbMaps = new Maps.TbMaps(loader("maps_tbmaps"));
        TbItems = new Items.TbItems(loader("items_tbitems"));
        TbMobs = new Mobs.TbMobs(loader("mobs_tbmobs"));
        TbAffixes = new Items.TbAffixes(loader("items_tbaffixes"));
        TbEquipment = new Items.TbEquipment(loader("items_tbequipment"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbConstants.ResolveRef(this);
        TbCharacters.ResolveRef(this);
        TbMaps.ResolveRef(this);
        TbItems.ResolveRef(this);
        TbMobs.ResolveRef(this);
        TbAffixes.ResolveRef(this);
        TbEquipment.ResolveRef(this);
    }
}

}
