
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.Items
{
public sealed partial class ItemTemplate : Luban.BeanBase
{
    public ItemTemplate(JsonElement _buf) 
    {
        Id = _buf.GetProperty("id").GetString();
        Name = _buf.GetProperty("name").GetString();
        ItemType = (Items.ItemType)_buf.GetProperty("item_type").GetInt32();
        Value = _buf.GetProperty("value").GetSingle();
        IconName = _buf.GetProperty("icon_name").GetString();
        Rarity = (Items.Rarity)_buf.GetProperty("rarity").GetInt32();
        { var __json0 = _buf.GetProperty("affixes"); int _n0 = __json0.GetArrayLength(); Affixes = new string[_n0]; int __index0=0; foreach(JsonElement __e0 in __json0.EnumerateArray()) { string __v0;  __v0 = __e0.GetString();  Affixes[__index0++] = __v0; }   }
    }

    public static ItemTemplate DeserializeItemTemplate(JsonElement _buf)
    {
        return new Items.ItemTemplate(_buf);
    }

    public readonly string Id;
    public readonly string Name;
    public readonly Items.ItemType ItemType;
    public readonly float Value;
    public readonly string IconName;
    public readonly Items.Rarity Rarity;
    public readonly string[] Affixes;
   
    public const int __ID__ = 238212187;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "itemType:" + ItemType + ","
        + "value:" + Value + ","
        + "iconName:" + IconName + ","
        + "rarity:" + Rarity + ","
        + "affixes:" + Luban.StringUtil.CollectionToString(Affixes) + ","
        + "}";
    }
}

}

