
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Items
{ 
    public enum Rarity
    {
        Common = 0,
        Rare = 1,
        Magic = 2,
        Epic = 3,
        Legendary = 4,
    }

} 

