
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.Items
{
public partial class TbEquipment
{
    private readonly System.Collections.Generic.Dictionary<string, Items.ItemTemplate> _dataMap;
    private readonly System.Collections.Generic.List<Items.ItemTemplate> _dataList;
    
    public TbEquipment(JsonElement _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, Items.ItemTemplate>();
        _dataList = new System.Collections.Generic.List<Items.ItemTemplate>();
        
        foreach(JsonElement _ele in _buf.EnumerateArray())
        {
            Items.ItemTemplate _v;
            _v = Items.ItemTemplate.DeserializeItemTemplate(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, Items.ItemTemplate> DataMap => _dataMap;
    public System.Collections.Generic.List<Items.ItemTemplate> DataList => _dataList;

    public Items.ItemTemplate GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Items.ItemTemplate Get(string key) => _dataMap[key];
    public Items.ItemTemplate this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

