
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.Characters
{
public sealed partial class CharacterInfo : Luban.BeanBase
{
    public CharacterInfo(JsonElement _buf) 
    {
        Id = _buf.GetProperty("id").GetString();
        Name = _buf.GetProperty("name").GetString();
        Level = _buf.GetProperty("level").GetInt32();
        Sprite = _buf.GetProperty("sprite").GetString();
        Stats = StatsInfo.DeserializeStatsInfo(_buf.GetProperty("stats"));
    }

    public static CharacterInfo DeserializeCharacterInfo(JsonElement _buf)
    {
        return new Characters.CharacterInfo(_buf);
    }

    public readonly string Id;
    public readonly string Name;
    public readonly int Level;
    public readonly string Sprite;
    public readonly StatsInfo Stats;
   
    public const int __ID__ = 183930611;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Stats?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "level:" + Level + ","
        + "sprite:" + Sprite + ","
        + "stats:" + Stats + ","
        + "}";
    }
}

}

